name: pesantren_app
description: A new Flutter project for Pondok Pesantren UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_login: ^6.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  carousel_slider: ^5.1.1
  markdown_widget: ^2.3.2+8
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  #flutter_markdown_plus: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/
    - assets/banners/
    - .env