// Struktur menu bercabang (tree)
const Map<String, dynamic> menuTree = {
  'PPI': {
    'Organ Struktural': [
      'Pusat Kepegawaian dan Pengawasan',
      'Pusat Pengawasan dan Pembinaan SDM Putri',
      'Pusat Penjaminan Mutu Pendidikan dan Pengajaran',
    ],
    'Organ Penyelenggara Pendidikan Formal': [
      'Taman Kanak-Kanak',
      'Taman Pendidikan Al-Qur\'an',
      'Madrasah Diniyah',
      'Madrasah Ibtidaiyah',
      'Madrasah Tsanawiyah Putra',
      'Madrasah Tsanawiyah Putri',
      'Madrasah Aliyah Putra',
      'Madrasah Aliyah Putri',
      'Madrasah Tahfizh Lil Athfal',
      'Institut Mujahadah dan Pembibitan',
      'Haromain',
      'Al Ittifaqiah Language Center',
    ],
    'Organ Penyelenggara Pendidikan Informal': [
      'LEMTATIQHI PA',
      'LEMTATIQHI PI',
      'LEBAH Putra',
      'LEBAH Putri',
      'LESGATRAM Putra',
      'LESGATRAM Putri',
      'Lembaga Muhadhoroh Putra',
      'Lembaga Muhadhoroh Putri',
      'LEMKAKIKU',
      'LEMKAPPI',
      'LERASI_LOGINTARU',
      'LK2PPI',
    ],
    'Organ Pengasuhan & Pengkaderan': [
      'DATSUHBINOSPI Putra',
      'DATSUHBINOSPI Putri',
      'Biro Pengkaderan, Beasiswa dan Kerjasama',
    ],
    'Organ Umum': [
      'ADKEU',
      'BIDDAPPMASSUL',
      'Bidang Kebersihan, Perairan, Pertamanan dan Lingkungan Hidup',
      'Bidang Sarana Prasarana, Perlistrikan dan Transportasi',
      'KESLOGMESS',
      'Klinik',
      'Bidang Keamanan, Ketertiban',
      'Hubungan Masyarakat dan Protokol',
    ],
    'Organ Struktural Otonom': [
      'IWAPPI',
      'PUSPAMAYA',
      'PUSDEM',
      'Avicenna Institute',
      'PUSDAP',
      'PBHU',
      'LPBI',
    ],
    'Organ Struktural Khusus': [],
  },
  // Tambah menu utama lain jika ada
};
